### ISSUE TITLE
모바일 채팅 문제

### ISSUE THREAD

**Issue by JongHyeok-Park** [JongHyeok-Park/FAQ_CHAT_Front#26]
모바일에서 채팅 보낼 때 입력한 내용이 전송한 후에도 그대로 남는 현상 발생. 아래 코드 수정 필요.

```
$("#submit").on("click", function () {
    sendMessage();
});

$("#messageInput").on("keydown", function (e) {
    if (e.key === "Enter") {
        e.preventDefault();
        sendMessage();
        $("#messageInput").val("");
    }
});
```

sendMessage() 함수는 submit event에만 남기고 messageInput keydown이벤트에서는 submit 클릭 이벤트를 호출하도록 만듭시다. 
그리고 $("#messageInput").val(""); 를 submit 클릭 이벤트로 옮겨야 합니다.

**Comment by thanhhien234** [comment]
수정했습니다
